### ISSUE TITLE
Survey questions do not display

### ISSUE THREAD

**Issue by LWest001** [codeforboston/urban-league-heat-pump-accelerator#493]
On survey page, dropdowns display but not the associated question.

![image](https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/93659375/f148e234-07ac-4fdd-801f-9cc11a8dcab8)

The issue is `SurveyComponent` feeding `survey_question.text` to prop `label` of `HeatPumpDropdown` and `HeatPumpTextField`, but the question text is stored under `survey_question.question`.

So in the following picture, the highlighted line should be `label={q.question}`.

![image](https://github.com/codeforboston/urban-league-heat-pump-accelerator/assets/93659375/7650c0a6-4d73-4910-b9e0-631809fa0ec2)

**Comment by mcarre20** [comment]
I think this was fixed by a change on the backend. I can see the questions now.

**Comment by LWest001** [comment]
> I think this was fixed by a change on the backend. I can see the questions now.

I'm still having the issue on main branch. Since you will be away and this is a relatively easy one, is it okay if I reassign to a new person who is getting familiar with project?
